#!/bin/bash
sshpass -p $1 ssh -o StrictHostKeyChecking=no root@45.55.78.123 "cd /var/www/PasswordBlocker/PasswordBlocker; cat save_pid.txt | xargs kill -9; git pull; source /etc/apache2/envvars; (nohup apache2 -X > my.log 2>&1 &) ; ps -A | grep apache2 | awk '{print \$1}' > save_pid.txt"



